import { Theme } from '../types';

export const themes: Record<string, Theme> = {
  default: {
    name: 'default',
    displayName: 'Aura',
    properties: {
      '--color-bg-main': '#020617',
      '--color-bg-card': 'rgba(15, 23, 42, 0.7)',
      '--color-border': 'rgba(56, 189, 248, 0.2)',
      '--color-text-primary': '#e2e8f0',
      '--color-text-secondary': '#94a3b8',
      '--color-text-tertiary': '#475569',
      '--color-primary-from': '#38bdf8',
      '--color-primary-to': '#0ea5e9',
      '--color-primary-text': '#e0f2fe',
      '--color-status-healthy-bg': 'rgba(34, 197, 94, 0.2)',
      '--color-status-healthy-text': '#4ade80',
      '--color-status-degraded-bg': 'rgba(245, 158, 11, 0.2)',
      '--color-status-degraded-text': '#facc15',
      '--color-status-error-bg': 'rgba(239, 68, 68, 0.2)',
      '--color-status-error-text': '#f87171',
    },
  },
  engineer: {
    name: 'engineer',
    displayName: 'Cygnus',
    properties: {
      '--color-bg-main': '#000000',
      '--color-bg-card': 'rgba(22, 22, 22, 0.7)',
      '--color-border': 'rgba(0, 255, 13, 0.2)',
      '--color-text-primary': '#f0f0f0',
      '--color-text-secondary': '#a0a0a0',
      '--color-text-tertiary': '#555555',
      '--color-primary-from': '#00ff41',
      '--color-primary-to': '#00ff41',
      '--color-primary-text': '#f0f0f0',
      '--color-status-healthy-bg': 'rgba(0, 255, 13, 0.2)',
      '--color-status-healthy-text': '#00ff41',
      '--color-status-degraded-bg': 'rgba(255, 165, 0, 0.2)',
      '--color-status-degraded-text': '#ffa500',
      '--color-status-error-bg': 'rgba(255, 0, 0, 0.2)',
      '--color-status-error-text': '#ff0000',
    }
  },
  support: {
    name: 'support',
    displayName: 'Orion',
    properties: {
        '--color-bg-main': '#1e1e2f',
        '--color-bg-card': 'rgba(41, 41, 61, 0.7)',
        '--color-border': 'rgba(138, 92, 245, 0.2)',
        '--color-text-primary': '#d9d9f0',
        '--color-text-secondary': '#a9a9d0',
        '--color-text-tertiary': '#696980',
        '--color-primary-from': '#8a5cf5',
        '--color-primary-to': '#6d28d9',
        '--color-primary-text': '#f5f3ff',
        '--color-status-healthy-bg': 'rgba(52, 211, 153, 0.2)',
        '--color-status-healthy-text': '#34d399',
        '--color-status-degraded-bg': 'rgba(251, 191, 36, 0.2)',
        '--color-status-degraded-text': '#fbbf24',
        '--color-status-error-bg': 'rgba(248, 113, 113, 0.2)',
        '--color-status-error-text': '#f87171',
    }
  },
  analyst: {
      name: 'analyst',
      displayName: 'Vela',
      properties: {
        '--color-bg-main': '#0f172a',
        '--color-bg-card': 'rgba(30, 41, 59, 0.7)',
        '--color-border': 'rgba(71, 85, 105, 0.4)',
        '--color-text-primary': '#cbd5e1',
        '--color-text-secondary': '#94a3b8',
        '--color-text-tertiary': '#475569',
        '--color-primary-from': '#a371f7',
        '--color-primary-to': '#8952E3',
        '--color-primary-text': '#f0f0f0',
        '--color-status-healthy-bg': 'rgba(34, 197, 94, 0.2)',
        '--color-status-healthy-text': '#4ade80',
        '--color-status-degraded-bg': 'rgba(245, 158, 11, 0.2)',
        '--color-status-degraded-text': '#facc15',
        '--color-status-error-bg': 'rgba(239, 68, 68, 0.2)',
        '--color-status-error-text': '#f87171',
      }
  },
  operator: {
      name: 'operator',
      displayName: 'Scorpius',
      properties: {
        '--color-bg-main': '#171717',
        '--color-bg-card': 'rgba(38, 38, 38, 0.7)',
        '--color-border': 'rgba(249, 115, 22, 0.3)',
        '--color-text-primary': '#e5e5e5',
        '--color-text-secondary': '#a3a3a3',
        '--color-text-tertiary': '#525252',
        '--color-primary-from': '#fb923c',
        '--color-primary-to': '#f97316',
        '--color-primary-text': '#fff7ed',
        '--color-status-healthy-bg': 'rgba(74, 222, 128, 0.2)',
        '--color-status-healthy-text': '#4ade80',
        '--color-status-degraded-bg': 'rgba(250, 204, 21, 0.2)',
        '--color-status-degraded-text': '#facc15',
        '--color-status-error-bg': 'rgba(220, 38, 38, 0.2)',
        '--color-status-error-text': '#ef4444',
      }
  }
};
